### ISSUE TITLE
您好，请问在不考虑few-shot的情况下，只再源数据集预训练模型时，加入标签语义和不加标签语义相比，模型效果有没有区别

### ISSUE THREAD

**Issue by rzhub** [TianWuYuJiangHenShou/LabelSemantics#10]
您好，请问在不考虑few-shot的情况下，只再源数据集预训练模型时，加入标签语义和不加标签语义相比，模型效果有没有区别

**Comment by TianWuYuJiangHenShou** [comment]
你实验下就知道了

**Comment by rzhub** [comment]
我在另一个ner模型上加入了这种标签语义，效果提升了0.5%（F1），但没有在few-shot数据下做实验，不知道有没有效果
