### ISSUE TITLE
关于Label BERT Encoder权重更新的疑问

### ISSUE THREAD

**Issue by lairongxuan** [TianWuYuJiangHenShou/LabelSemantics#3]
你好，有个问题请教一下：
paper在针对标签进行编码的时候，利用了额外的 `Label BERT Encoder` 进行编码，想请问这个编码器在训练过程中是否参与权重更新？

**Comment by Emma1066** [comment]
我也有相同疑问。我看paper里写的是要更新Label BERT Encoder的，但是源码里却没有更新。

**Comment by TianWuYuJiangHenShou** [comment]
是的，要更新权重的。代码已做了更新
