### ISSUE TITLE
您好，可以简单展示下train.txt数据集的样子吗？

### ISSUE THREAD

**Issue by magicmashroom0** [TianWuYuJiangHenShou/LabelSemantics#9]
如果展示数据集比较困难的话，以下是我的数据集样例，可否作为LabelSemantics.py的输入呢？
房 B_pro
室 I_pro
结 I_pro
消 I_pro
融 I_pro
和 O
起 B_pro
搏 I_pro
器 I_pro
植 I_pro
入 I_pro
作 O
为 O

**Comment by TianWuYuJiangHenShou** [comment]
格式无所谓的，你自己换一下数据处理的代码就行。只要代码能跑起来

**Comment by magicmashroom0** [comment]
感谢您的回复，在运行LabelSemantics.py时，在157行的pooler_output = outputs.pooler_output会报错。提示outputs没有pooler_output，这个outputs是tuple，本身不自带这个属性，所以想问下这个定义的pooler_output是代表什么呢？

**Comment by TianWuYuJiangHenShou** [comment]
> 感谢您的回复，在运行LabelSemantics.py时，在157行的pooler_output = outputs.pooler_output会报错。提示outputs没有pooler_output，这个outputs是tuple，本身不自带这个属性，所以想问下这个定义的pooler_output是代表什么呢？

你研究下huggingface 的bert源码就知道这个pooler_output是啥了，没有应该是你加载的model没有这个参数
